name: Terraform CI Validation

on:
  push:
    branches:
      - main
      - fix/*
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Format and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false   # optional, avoids wrapper scripts


      - name: Terraform checks (explicit projects)
        shell: bash
        run: |
          set -e

          TERRAFORM_PROJECTS=(
            project-01-ec2-terraform
            project-02-s3-static-site
            project-03-cloudwatch-alarm
            project-04-iam-user-automation
          )

          for dir in "${TERRAFORM_PROJECTS[@]}"; do
            echo "======================================"
            echo "Running Terraform checks in $dir"
            echo "======================================"

            terraform fmt -check -recursive "$dir"

            cd "$dir"
            terraform init -backend=false -input=false
            terraform validate
            cd ..
          done
